export enum DetailCodeEnum {
  // 400
  NOT_A_STRING = 'NOT_A_STRING',

  DATA_DUPLICATE = 'DATA_DUPLICATE',

  NO_USER = 'NO_USER',
  NO_PAGE = 'NO_PAGE',
  DUPLICATE_REQUEST = 'DUPLICATE_REQUEST',

  // 401
  TOKEN_MISMATCH = 'TOKEN_MISMATCH',

  //404
  REQUEST_DATA_NOT_EXIST = 'REQUEST_DATA_NOT_EXIST',
}
