export enum ErrorCodeEnum {
  //400 Bad Request
  INVALID_DATA_TYPE = 'INVALID_DATA_TYPE',
  INVALID_DATA = 'INVALID_DATA',

  //401
  UNAUTHORIZED_REQUEST = 'UNAUTHORIZED_REQUEST',

  //404 Not Found
  DATA_NOT_EXISTS = 'DATA_NOT_EXISTS',
}
